sbatch train_dermofit10p.sbatch
sbatch train_dermofit30p.sbatch
sbatch train_dermofit50p.sbatch
sbatch train_dermofit70p.sbatch
sbatch train_dermofit99p.sbatch

sbatch train_dermofitwAE10p.sbatch
sbatch train_dermofitwAE30p.sbatch
sbatch train_dermofitwAE50p.sbatch
sbatch train_dermofitwAE70p.sbatch
sbatch train_dermofitwAE99p.sbatch