# Resnet50
sbatch Seg_APP_seed73_resnet50_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet50_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet50_unet_woAE.SBATCH

sbatch Seg_APP_seed73_resnet50_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet50_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet50_unetpp_woAE.SBATCH

sbatch Seg_APP_seed211_resnet50_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet50_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet50_unet_woAE.SBATCH

sbatch Seg_APP_seed211_resnet50_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet50_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet50_unetpp_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet50_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet50_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet50_unet_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet50_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet50_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet50_unetpp_woAE.SBATCH

# Resnet34
sbatch Seg_APP_seed73_resnet34_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet34_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet34_unet_woAE.SBATCH

sbatch Seg_APP_seed73_resnet34_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet34_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet34_unetpp_woAE.SBATCH

sbatch Seg_APP_seed211_resnet34_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet34_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet34_unet_woAE.SBATCH

sbatch Seg_APP_seed211_resnet34_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet34_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet34_unetpp_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet34_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet34_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet34_unet_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet34_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet34_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet34_unetpp_woAE.SBATCH

# Resnet18
sbatch Seg_APP_seed73_resnet18_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet18_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet18_unet_woAE.SBATCH

sbatch Seg_APP_seed73_resnet18_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet18_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet18_unetpp_woAE.SBATCH

sbatch Seg_APP_seed211_resnet18_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet18_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet18_unet_woAE.SBATCH

sbatch Seg_APP_seed211_resnet18_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet18_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet18_unetpp_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet18_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet18_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet18_unet_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet18_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet18_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet18_unetpp_woAE.SBATCH

# Resnet101
sbatch Seg_APP_seed73_resnet101_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet101_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet101_unet_woAE.SBATCH

sbatch Seg_APP_seed73_resnet101_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet101_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed73_resnet101_unetpp_woAE.SBATCH

sbatch Seg_APP_seed211_resnet101_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet101_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet101_unet_woAE.SBATCH

sbatch Seg_APP_seed211_resnet101_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet101_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed211_resnet101_unetpp_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet101_unet_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet101_unet_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet101_unet_woAE.SBATCH

sbatch Seg_APP_seed1234_resnet101_unetpp_gelu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet101_unetpp_relu_wAE.SBATCH
sbatch Seg_APP_seed1234_resnet101_unetpp_woAE.SBATCH